macros = 'macros/.macros.test.ts'

[[packages]]
location = 'lib'
entry = '**/*.ts'
exclude = "**/*.test.ts"
environment = 'anywhere'

[[packages]]
location = 'macros'
entry = '**/*.ts'
exclude = "**/*.test.ts"
environment = 'anywhere'

